files:
  include: 'source/**/*.scss'
rules:
  class-name-format: [0]
  brace-style: [0]
  force-pseudo-nesting: [0]
  force-element-nesting: [0]
  empty-line-between-blocks: [0]
  no-vendor-prefixes: [0]
  no-color-literals: [0]
  no-important: [0]
  no-ids: [0]
